export DOTFILES_REPOS="/Users/ashim/resources/repos"
export DOTFILES_SOFTWARE_INSTALL_PREFIX="/Users/ashim/resources/software/installed/"
export DOTFILES_SOFTWARE_STANDALONE="/Users/ashim/resources/software/standalone/"
export DOTFILES_GTD="/Users/ashim/private/gtd/"
export DOTFILES_KNOWL="/Users/ashim/private/knowl/"
export DOTFILES_DIARY="/Users/ashim/private/diary/"
export DOTFILES_PYENVS="/Users/ashim/resources/software/pyenvs/"
export DOTFILES_WWW="/Users/ashim/public/www/"
export DOTFILES_PERSONAL_WORKSPACE="/Users/ashim/ashim"
export DOTFILES_CLINIC_WORKSPACE="/Users/ashim/clinic"
# Note: FREEPLANE_PATH exported by home.sh
