export DOTFILES_REPOS="~/resources/repos"
export DOTFILES_SOFTWARE_INSTALL_PREFIX="~/resources/software/installed/"
export DOTFILES_SOFTWARE_STANDALONE="~/resources/software/standalone/"
export DOTFILES_GTD="~/private/gtd/"
export DOTFILES_KNOWL="~/private/knowl/"
export DOTFILES_DIARY="~/private/diary/"
export DOTFILES_PYENVS="~/resources/software/pyenvs/"
export DOTFILES_WWW="~/public/www/"
export DOTFILES_PERSONAL_WORKSPACE="~/ashim"
export DOTFILES_CLINIC_WORKSPACE="~/clinic"
export DOTFILES_FAMILY_WORKSPACE="~/family"
# Note: FREEPLANE_PATH exported by home.sh
